import { Injectable, Logger } from '@nestjs/common';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import { BOOKING_QUEUE_NAME, BOOKING_JOB_NAME } from '../queue.constants';
import { correlationStorage } from '../../../common/logger/correlation.store';

@Injectable()
export class BookingProducer {
  private readonly logger = new Logger(BookingProducer.name);

  constructor(
    @InjectQueue(BOOKING_QUEUE_NAME) private readonly bookingQueue: Queue
  ) {}

  /**
   * Pushes a booking processing job onto the queue.
   * Returns the enqueued job ID.
   */
  async enqueueBooking(bookingId: string): Promise<string> {
    const requestId = correlationStorage.getStore();
    this.logger.log(`Enqueuing booking processing job: bookingId=${bookingId} | requestId=${requestId || 'none'}`);
    try {
      const job = await this.bookingQueue.add(
        BOOKING_JOB_NAME,
        { bookingId, requestId },
        {
          attempts: 3,
          backoff: {
            type: 'exponential',
            delay: 1000,
          },
          removeOnComplete: true,
          removeOnFail: {
            count: 100, // Keep last 100 failed jobs for auditing/debugging
          },
        }
      );

      if (!job.id) {
        throw new Error('Enqueued job has no ID generated by BullMQ');
      }

      this.logger.log(`Successfully enqueued job. jobId=${job.id}, bookingId=${bookingId}`);
      return job.id;
    } catch (error) {
      this.logger.error(
        `Failed to enqueue booking job: bookingId=${bookingId}`,
        error instanceof Error ? error.stack : error
      );
      throw error;
    }
  }
}
